name: Battlecraft
version: ${fullVersion}
description: Plugin de pvp base do Battlebits
authors: [GustavoInacio]
main: br.com.battlebits.battlecraft.Battlecraft
depend: [Commons, ProtocolLib]
api-version: "1.12"